
services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=analytix_hive_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d analytix_hive_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend-codes
    ports:
      - "8000:8000"
    volumes:
      - ./backend-codes:/app
    env_file:
      - ./backend-codes/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend-codes
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
